// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
	// Static-assets fetcher bound in wrangler.jsonc; used by worker.js (env.ASSETS.fetch).
	ASSETS: Fetcher;
}
